pose0: icp_pose/monitored
pose0_differential: false
pose0_config: [
    true, true, true,
    true, true, true,
    false, false, false,
    false, false, false,
    false, false, false
]

# odom0: wheel_odom/monitored
# odom0_differential: false
# odom0_config: [false, false, false,
#                false, false, false,
#                true,  true,  false,
#                false, false, true,
#                false, false, false]

imu0: vn100/imu_wori_wcov/monitored
imu0_differential: false
imu0_config: [false, false, false,
              false,  false,  false,
              false, false, false,
              true,  true,  true,
              false, false, false]

imu0_remove_gravitational_acceleration: true

# FIXME: don't hardcode this
# For dataset O:
# initial_state: [
#     0, 0, 0,
#     0, 0, 0,
#     0, 0, 0,
#     0, 0, 0,
#     0, 0, 0
# ]
# For dataset B:
# initial_state: [
#     -2.53, -0.05, 0.014,
#     0.0026, -0.006, 0.077,
#     0, 0, 0,
#     0, 0, 0,
#     0, 0, 0
# ]

# For dataset D:
initial_state: [
    -7.88, 214.7, 1.99,
    0.0026, -0.006, 0.077,
    0, 0, 0,
    0, 0, 0,
    0, 0, 0
]

# process_noise_covariance: [0.05, 0,    0,    0,    0,    0,
#                             0,   0.05,  0,    0,    0,    0,
#                             0,    0,    0,    0,    0,    0,
#                             0,    0,    0,   0.01,  0,    0,
#                             0,    0,    0,    0,   0.01,  0,
#                             0,    0,    0,    0,    0,   0.01]

